# https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8-assignment-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi